### ISSUE TITLE
项目详情页（复杂）

### ISSUE THREAD

**Issue by 521xueweihan** [HelloGitHub-Team/geese#10]
为开源项目贴标：

我觉得 GitHub 项目的原始信息过于单薄，所以 HG 详情页想把用户在寻找项目时最关心的元素提取并醒目地展示出来，比如：Star 数、代码语言、是否包含中文、是否活跃、许可类型。

同时项目的分类过于模糊，月刊那种单一的分类十分宽泛，所以我为每个项目增加了标签，方便用户寻找同标签的项目（水平）

最后，“HG 评分”是我们的核心，它会根据 GitHub 上的各种数据以及我们用户的评分、点击、点赞、分享、收藏，计算出来一个综合评估项目受喜爱程度的数值。

原型图：

![Image](https://user-images.githubusercontent.com/8255800/176983736-5a8c7f30-2f7b-4251-bd78-07324ee7769d.jpeg)

接口：https://local.api.hellogithub.com/docs#/repository/detail_v1_repository_detail__rid___get

示例：https://local.api.hellogithub.com/v1/repository/detail/a4279670afea4b6987dc3d045876316a/

注意：图上标记了元素对应的接口字段，没有的字段可暂时先实现展示效果。

**Comment by 521xueweihan** [comment]
@weoking 详情页展示原型图完成，对应接口开发完成，前端可进行开发。

**Comment by 521xueweihan** [comment]
任务释放，重新认领。

**Comment by zhangzhonghe** [comment]
@521xueweihan 我想认领，预估 5 天。

**Comment by 521xueweihan** [comment]
@zhangzhonghe 认领

可通过 PR 方式贡献代码，原型图中基本标记了响应返回的数据。

**Comment by zhangzhonghe** [comment]
有几个问题需要确认下：

![2e4361f8f251f52a8eb55d3dc1e1789](https://user-images.githubusercontent.com/38434641/178169246-76029544-f3d8-407b-b927-10d581abb2f9.png)

1. 这个圈是指分享者的头像吗？

![d17586f21e9021d99c4e750727c4135](https://user-images.githubusercontent.com/38434641/178169360-c2e1a20b-8ad9-44d7-8251-6a94153bb811.png)

2. 这个字段是不是没有，在接口文档中没有发现。

![096dc14979a8baa0d71f1815a1c049d](https://user-images.githubusercontent.com/38434641/178169449-f6e8fd95-1571-4e19-8a71-264ab9966bb2.png)

3. 这个区域都是展示 title 字段的吗？

![eaf37560d974ae463d3889a7a82d599](https://user-images.githubusercontent.com/38434641/178169510-793c0fff-b91b-4cff-bc06-1744fa895213.png)

4. 点击更多需要显示什么，怎么交互？

![6d160573f9f25024b9870ace697cd41](https://user-images.githubusercontent.com/38434641/178169561-ad752a9c-6c30-4df4-851e-25e41591048e.png)

5. 评论区的话，前端先实现展示效果吗？

**Comment by 521xueweihan** [comment]
@zhangzhonghe 搞起，关于您的问题回复如下：

1、这个圈是指分享者的头像吗？
是的，对应接口的 share_user.avatar 。

2、score 这个字段是不是没有，在接口文档中没有发现。
是的，可以先实现效果，这个字段依赖的数据较多，正在开发中。预计本周三完成。

3、这个区域都是展示 title 字段的吗？
我的想法是这样的，但如果如果不好看的话。可以尝试用 descption 进行填充（展示的样式可以调整）。

4、点击更多需要显示什么，怎么交互？
“点击”更多后，该部分同样的背景色展开，扩充一行即可。该部分展示 fork、issues 数等

5、评论区的话，前端先实现展示效果吗？
前端留好评论区域即可，该部分由其它小伙伴认领和实现。

我设计时，参考的示意图：



![Image](https://user-images.githubusercontent.com/8255800/178171419-4a854033-7682-4ecf-ae38-e432a8b7c539.png)

**Comment by zhangzhonghe** [comment]
@521xueweihan 了解了，开始搞起~

**Comment by 521xueweihan** [comment]
第一期完成，后续再做细节优化

**Comment by 521xueweihan** [comment]
@521xueweihan 二期：
代码、点赞、分享

**Comment by 521xueweihan** [comment]
> @521xueweihan 二期： 代码、点赞、分享

已完成
