### ISSUE TITLE
本地开发怎样启动这个项目呢？

### ISSUE THREAD

**Issue by exposir** [HelloGitHub-Team/geese#104]
yarn dev 

<img width="1075" alt="image" src="https://user-images.githubusercontent.com/33340988/233775250-8fd98637-1dca-4aea-badb-5a3562a1864b.png">

**Comment by 521xueweihan** [comment]
@exposir 
启动后可能会遇到的问题：

1. 跨域问题：请检查前端服务启动端口为：3000、host 为 localhost、127.0.0.1
2. 图片无法展示：在本地 hosts 文件末尾添加一行 127.0.0.1 dev.hg.com，随后访问 http://dev.hg.com:3000/

如果无法解决，可以截图发一下开发者模式下的接口响应
