### ISSUE TITLE
跨域问题

### ISSUE THREAD

**Issue by re-doc** [HelloGitHub-Team/geese#107]
本地启动跨域，截图如下
![屏幕截图 2023-05-12 225708](https://github.com/HelloGitHub-Team/geese/assets/41844546/d955fc29-a009-4fdc-a2be-13a4342e31f0)

**Comment by 521xueweihan** [comment]
@re-doc 

跨域问题：请检查前端服务启动端口为：3000、host 为 localhost、127.0.0.1
图片无法展示：在本地 hosts 文件末尾添加一行 127.0.0.1 dev.hg.com，随后访问 http://dev.hg.com:3000/

**Comment by re-doc** [comment]
解决了，修改上面的两条规则后，还需要关闭代理或者配置代理规则
