### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by Pleasurecruise** [HelloGitHub-Team/geese#151]
这个Echart库服务端渲染的问题需要怎么解决
![image](https://github.com/user-attachments/assets/d65d5509-2367-4ae8-a4cb-f7a22908b4d1)

**Comment by 521xueweihan** [comment]
@Pleasurecruise 你是不是修改了代码？

这个异常是因为你在服务器端，调用了 windows 对象（用于判断客户端）
