### ISSUE TITLE
用户首页

### ISSUE THREAD

**Issue by 521xueweihan** [HelloGitHub-Team/geese#29]
![](https://user-images.githubusercontent.com/8255800/187850025-281ddd6e-3b66-4e0c-9822-4267355e36f6.png)

### 1、基本信息和动态

<img width="399" alt="image" src="https://user-images.githubusercontent.com/8255800/187849590-2d0480dd-82fd-46d9-b34a-795921e6460e.png">

- 接口：https://local.api.hellogithub.com/docs#/user/user_profile_v1_user__uid__get

**userInfo：中的 in_person 为 True 才显示 收藏 和 评论 入口，同时：右上角增加一个“登出”的按钮**

动态：包含用户头像（看样式难堪的话可取消）、贡献动态、点赞（未实现），不支持翻页，所有人（非登录状态）均可浏览，

### 2、收藏

<img width="517" alt="image" src="https://user-images.githubusercontent.com/8255800/187849608-74f00040-2e67-4049-a42b-83f8d8879890.png">

- 接口：https://local.api.hellogithub.com/docs#/user/user_collection_v1_user__uid__collection__get

需要带翻页，item 的样式可以自由调整和优化

### 3、评论

<img width="582" alt="image" src="https://user-images.githubusercontent.com/8255800/187849653-e9843e9d-f4ee-45d4-84cc-9ed9f7b1ddac.png">

- 接口：https://local.api.hellogithub.com/docs#/user/user_comment_v1_user__uid__comment__get

需要带翻页，item 的样式可以自由调整和优化

申诉接口暂未实现，暂时用语雀表单收集代替。

地址：https://hellogithub.yuque.com/forms/share/d268c0c0-283f-482a-9ac8-939aa8027dfb

**Comment by zhangzhonghe** [comment]
@521xueweihan **贡献**一栏的接口没有吗？

**Comment by 521xueweihan** [comment]
> @521xueweihan **贡献**一栏的接口没有吗？

@zhangzhonghe 我把动态和贡献 tab 合成了一个，收藏和评论接口已经完成了

**Comment by 521xueweihan** [comment]
@zhangzhonghe 分页组件我优化了一下下，现在很通用了：https://github.com/HelloGitHub-Team/geese/commit/5ae249c0fcbb0605ff3c30a05186df15bc05c5b7#diff-c306f8728da2a9e5108ca18111ce1f0d8126c4df0955cdaf3b211c5443b9c545

**Comment by zhangzhonghe** [comment]
> @zhangzhonghe 分页组件我优化了一下下，现在很通用了：[5ae249c#diff-c306f8728da2a9e5108ca18111ce1f0d8126c4df0955cdaf3b211c5443b9c545](https://github.com/HelloGitHub-Team/geese/commit/5ae249c0fcbb0605ff3c30a05186df15bc05c5b7#diff-c306f8728da2a9e5108ca18111ce1f0d8126c4df0955cdaf3b211c5443b9c545)

OK
