### ISSUE TITLE
[体验优化] 主站 post 所有人建议采用项目作者，而非分享人

### ISSUE THREAD

**Issue by QingZ11** [HelloGitHub-Team/geese#31]
![image](https://user-images.githubusercontent.com/38887077/186328872-ccca6308-2d91-4370-b19c-e9914fff4470.png)

项目前期的话，应该是蛋蛋分享为主（超过 99.99%），所以一旦采用分享人作为主页的显示，会降低主站的人气感，造成这个网站没人活跃在上面除了发起人。

建议先以作者作为主页显示，以及主站后期有人进行评论可以以最后评论人进行主页展示（根据运营需求来）

**Comment by 521xueweihan** [comment]
建议采纳，开发完成。

效果查看：https://dev.hg.hellogithub.com/

<img width="1274" alt="截屏2022-09-05 20 01 28" src="https://user-images.githubusercontent.com/8255800/188470904-6553f312-9db9-4416-9399-a66343becfc7.png">
