### ISSUE TITLE
排行榜

### ISSUE THREAD

**Issue by 521xueweihan** [HelloGitHub-Team/geese#40]
这个需求主要是为了让新网站能够继续提供：编程语言、服务器、数据库排行榜的功能。

旧网站排行榜地址（PC 访问）：https://hellogithub.com/report/tiobe/

**要求**：
- 排行榜入口在 header 月刊的右侧，需要优化搜索框的手机端的适配
- path 延续之前的不变
- SSR
- 另外下图中的查询按钮，可改成月份数字变化自动刷新

![Image](https://user-images.githubusercontent.com/8255800/189144388-f744756d-4531-4895-a0df-c11982dcf7dc.png)

需要延续就网站的地址，所以 path 如上。具体样式可以参考 GitHub Trending：https://github.com/trending/python?since=daily

**接口**：
- tiobe：https://local.api.hellogithub.com/docs#/report/tiobe_rank_v1_report_tiobe__get
- netcraft：https://local.api.hellogithub.com/docs#/report/netcraft_rank_v1_report_netcraft__get
- db：https://local.api.hellogithub.com/docs#/report/db_rank_v1_report_db__get

**month(可选参数)：请求的月份，不传则返回最新一期排行榜的数据。**

**month_list：返回的数据，代表有排行榜数据的月份。**

**Logo**：
- tiobe：https://img.hellogithub.com/logo/tiobe.jpg
- netcraft：https://img.hellogithub.com/logo/netcraft.jpg
- db：https://img.hellogithub.com/logo/db.jpg

**Comment by xp12047** [comment]
真棒！但是俺想知道啥叫cms？方便给些链接参考下嘛，谢谢

**Comment by 521xueweihan** [comment]
@xp12047 https://zh.wikipedia.org/zh-cn/%E5%86%85%E5%AE%B9%E7%AE%A1%E7%90%86%E7%B3%BB%E7%BB%9F

**Comment by xp12047** [comment]
> @xp12047 https://zh.wikipedia.org/zh-cn/%E5%86%85%E5%AE%B9%E7%AE%A1%E7%90%86%E7%B3%BB%E7%BB%9F

谢谢😊
