### ISSUE TITLE
Modal 框有交互问题

### ISSUE THREAD

**Issue by cqh963852** [HelloGitHub-Team/geese#46]
https://user-images.githubusercontent.com/17702287/190551257-b3600c6e-bfe7-4bdc-b293-21578df8ad09.mp4

**Comment by cqh963852** [comment]
复现步骤
- 点击分享项目，弹出模态框
- 点击网页外，再选中网页

模态框可能会消失。

**Comment by zhangzhonghe** [comment]
我来看下这个 BUG

**Comment by 521xueweihan** [comment]
@zhangzhonghe 好的，这个组件应该是照搬的 daisyui 组件：
https://github.com/saadeghi/daisyui/blob/master/src/components/styled/modal.css

代码如果有冗余的部分可直接删除哈。

**Comment by zhangzhonghe** [comment]
> @zhangzhonghe 好的，这个组件应该是照搬的 daisyui 组件： https://github.com/saadeghi/daisyui/blob/master/src/components/styled/modal.css
> 
> 代码如果有冗余的部分可直接删除哈。

好的，之前有看过代码
