### ISSUE TITLE
MDRender 渲染组件的代码高亮，无法切换黑暗模式

### ISSUE THREAD

**Issue by 521xueweihan** [HelloGitHub-Team/geese#47]
# MDRender 渲染组件切换黑暗模式问题

我尝试让组件接收是否为黑暗模式状态的参数：
1. 组件无 localStorage、windows 对象
2. 无法判断当前是否处于黑暗模式

另外，我发现 MDRender 该组件无法渲染「无序列表」

**Comment by zhangzhonghe** [comment]
我首先想到的是设置全局样式去影响 MDRender 中的样式。

当设置暗黑模式的时候会在 html 标签上设置一个 dark 类：

```html
<html class="dark">
  ...other code
</html>
```

所以可以通过以下方式对 MDRender 的样式进行覆盖：

```css
.dark .some-class-name {
  ...style code
}
```

**Comment by 521xueweihan** [comment]
@zhangzhonghe 收到，我试试～

**Comment by 521xueweihan** [comment]
这块我感觉替换 code 的 css 不如传递 dark 的状态，然后选择不同的 code 主题。

但是我不知道怎么设置一个全局可变变量，我试了 document、windows、localStorage 都会出现组件中没有这个对象的问题。

**Comment by RJM1996** [comment]
> 

<img width="836" alt="image" src="https://user-images.githubusercontent.com/33800707/191652642-51d19b07-88a0-4430-82d7-96d231e17def.png">
<img width="664" alt="image" src="https://user-images.githubusercontent.com/33800707/191652738-0e067da0-e1c0-4d9f-a894-ace9519cf100.png">
<img width="718" alt="image" src="https://user-images.githubusercontent.com/33800707/191652824-faebd116-012b-4c38-8a41-0a6492ad43bd.png">

可以使用 Context 传递 theme 信息

**Comment by 521xueweihan** [comment]
@RJM1996  学到了🙏
