### ISSUE TITLE
翻页组件（简单）

### ISSUE THREAD

**Issue by 521xueweihan** [HelloGitHub-Team/geese#5]
首页 items 末尾增加翻页功能，我还没想好用那种翻页组件，索性由开发者决定吧！
1. 无触发到底自动触发或手动点击“加载更多”实现加载更内容
2. 下一页、上一页翻页组件

实现那种由认领者决定。

接口：https://local.api.hellogithub.com/docs#/home/home_v1__get

**Comment by weoking** [comment]
<img width="843" alt="image" src="https://user-images.githubusercontent.com/47032621/176891763-f2f1439f-969b-40ee-81cb-cdefa93df370.png">
感觉可以固定这些部分，然后往下滚实现自动触发翻页，模仿黑客说的效果

**Comment by 521xueweihan** [comment]
@weoking 好主意，搞起！
