### ISSUE TITLE
搜索组件（中等）

### ISSUE THREAD

**Issue by 521xueweihan** [HelloGitHub-Team/geese#6]
搜索组件支持：输入联想（suggest）、搜索

接口：https://local.api.hellogithub.com/docs#/search

搜索组件在页面上展示的位置：在 header 上 logo 的右边一点

注意：需考虑兼容不同屏幕尺寸，既 tailwind 的 md、lg 等可参考已有代码

**Comment by 521xueweihan** [comment]
@RJM1996 认领

**Comment by RJM1996** [comment]
好的，我看下 @[521xueweihan](https://github.com/521xueweihan)

> @RJM1996 我要请你进入「geese」项目了，后面就可以直接通过分支提交代码了。
> 
> #20 已经合并，本地测试发现的问题：
> 
> 1. 代码没有通过 type 检查，可以本地执行 `yarn typecheck` 尝试解决检查的异常
> 2. placeholder 小屏时太长和 搜索的 icon 有重叠
> 
> <img alt="image" width="491" src="https://user-images.githubusercontent.com/8255800/177583624-c11201ff-9fba-4655-93ea-8f75af2ae9cd.png">

**Comment by 521xueweihan** [comment]
已完成
