### ISSUE TITLE
移动端点击后样式一直为 hover 下的样式

### ISSUE THREAD

**Issue by 521xueweihan** [HelloGitHub-Team/geese#62]
上述问题出现在移动端访问时，问题的页面和具体位置如下：
- [月刊](https://hellogithub.com/periodical/volume/77)的上一页、下一页，点击后一直处于 hover 状态下的样式
<img width="461" alt="image" src="https://user-images.githubusercontent.com/8255800/194682580-592bfbab-5dba-4b75-a0bd-241725421efe.png">

- [项目详情](https://hellogithub.com/repository/aedeccc0e75841ed8c4c342662224684)的 moreInfo 组件点击“展开”，收缩一直处于 hover 状态下的样式
<img width="285" alt="image" src="https://user-images.githubusercontent.com/8255800/194682561-0a57da10-cf52-4ed1-815c-72b6ba67a557.png">

**Comment by lalawow** [comment]
You can check this comment on tailwind's board . It might be able to solve your issue.
https://github.com/tailwindlabs/tailwindcss/discussions/1739#discussioncomment-3630717

**Comment by cqh963852** [comment]
> * [月刊](https://hellogithub.com/periodical/volume/77)的上一页、下一页，点击后一直处于 hover 状态下的样式

https://github.com/vercel/next.js/issues/33060

关于 link 的 focus 状态，是 nextjs 的设计

**Comment by 521xueweihan** [comment]
@lalawow @cqh963852 
感谢帮助，已按照 @lalawow 提供的解决方案解决「移动端 hover 样式的异常」

解决办法：
```
// tailwind.config.js
module.exports = {
  future: {
    hoverOnlyWhenSupported: true,
  },
  // ...
}
```

**提示**：该解决方案 tailwind 必须为 3.1 版本以上
