### ISSUE TITLE
自适应优化

### ISSUE THREAD

**Issue by 521xueweihan** [HelloGitHub-Team/geese#65]
**优先级** ： Header > 广告组件 > 下拉框

## 大宽屏
1\. 宽屏 header 没有等比拉伸，logo 应该多出内容一些
2\. 右边栏的广告组件，图片展示不完整

<img width="806" alt="截屏2022-10-09 09 28 53" src="https://user-images.githubusercontent.com/8255800/194733318-4998f545-d32f-4554-ac55-5851cb481494.png">

3\. 宽屏下月刊的目录太宽了

<img width="816" alt="image" src="https://user-images.githubusercontent.com/8255800/194795003-36b6fed6-fc22-41bb-9e88-6ad1dca6d1fe.png">

## 小窄屏幕
1\. header 上的搜索框没有自动伸缩，需保证 左下拉框的和头像的完整
<img width="546" alt="image" src="https://user-images.githubusercontent.com/8255800/194794372-e0895e18-9a23-4dff-9717-cdc0cec9ad84.png">

2\. 项目详情右侧 score、评论按钮 顶出屏幕了

<img width="503" alt="image" src="https://user-images.githubusercontent.com/8255800/194794582-486e0c51-e9b3-4696-815c-0a2fd2de511f.png">

<img width="204" alt="image" src="https://user-images.githubusercontent.com/8255800/194794628-56278316-5d92-448d-8a50-cb913a05034d.png">

3\. 排行榜，中间 logo 部分伸缩（文字部分可以省略），保证两个下拉框的正常展示

<img width="269" alt="截屏2022-10-10 11 16 17" src="https://user-images.githubusercontent.com/8255800/194794792-0fa902f6-eb44-4b63-9360-9fb18e3922f6.png">

下来选项的内容不用换行

<img width="62" alt="image" src="https://user-images.githubusercontent.com/8255800/194794886-7087b849-5919-4e00-b52d-2846f363912f.png">

**Comment by 521xueweihan** [comment]
认领那个 bug 可以在这里留言，防止做重哈。

**Comment by cqh963852** [comment]
自适应通常是小屏幕设计优先。先有小屏幕的设计-> 中 -> 大。且小屏优先实现。遵循这个规则，通常不需要特殊开发。

**Comment by RJM1996** [comment]
200多的屏幕宽度是不是太极端了，一般没有手机屏幕这么窄吧

**Comment by 521xueweihan** [comment]
@RJM1996 是的，200 过于极端了。
尽量兼容一 270 左右吧，我看有个用户用老款 iphone 应该是 270 左右，展示有问题。

**Comment by 521xueweihan** [comment]
@521xueweihan 修复大屏幕 2

**Comment by RJM1996** [comment]
> 认领那个 bug 可以在这里留言，防止做重哈。

已修复：
1. 大宽屏 1
<img width="1629" alt="image" src="https://user-images.githubusercontent.com/33800707/195345176-edbacd38-9451-4bd7-80d7-084a539c8622.png">

3. 窄屏 1、3
<img width="434" alt="image" src="https://user-images.githubusercontent.com/33800707/195349125-8e252e65-749f-4542-9fa2-bb87438f3df0.png">

已提交到 i65-自适应优化 分支
