### ISSUE TITLE
右边栏：用户和网站状态（中等）

### ISSUE THREAD

**Issue by 521xueweihan** [HelloGitHub-Team/geese#7]
右边栏包含模块：
1. 用户状态（头像、级别、积分、签到？）
2. 网站状态（项目总数、用户总数）
3. 考虑设计赞助商栏
4. footer

![Image](https://user-images.githubusercontent.com/8255800/176984343-e402b6d1-5f0f-47f3-8c02-39c4467d5885.png)

主要开发工作：右边栏不随中心内容的滚动而滚动、展示占位方便后续接入数据。

接口：
1、用户状态：https://local.api.hellogithub.com/docs#/user/user_me_v1_user_me__get
```
nickname：昵称
avatar：头像
积分和等级先写死占位
```
2、网站状态：https://local.api.hellogithub.com/docs#/home/stats_v1_stats__get
```
repo_total：项目总数
user_total：用户总数
period_total：月刊总数
```

3、赞助位前端静态占个位即可，我得先去拉赞助拉不到，就不用这个功能了
4、静态

**Comment by 521xueweihan** [comment]
@xuyawen 认领

**Comment by 521xueweihan** [comment]
@xuyawen 接口开发完成，前端可以开始了。

**Comment by xuyawen** [comment]
好的



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年07月02日 11:07 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [HelloGitHub-Team/geese] 右边栏：用户和网站状态（中等） (Issue #7) |

@xuyawen 接口开发完成，前端可以开始了。

**Comment by 521xueweihan** [comment]
暂时完成，后续有赞助商需求再重新开启。

**Comment by 521xueweihan** [comment]
优化
1. 考虑在组件中使用 swr 保证用户信息和网站信息的及时更新。
2. 样式的改动需要考虑不同屏幕尺寸的适配。

**Comment by 521xueweihan** [comment]
已合并到 main 分支

优化建议：
1. 增加 loading 组件（src/components/loading)
