### ISSUE TITLE
[产品优化] 建议优化项目展示

### ISSUE THREAD

**Issue by QingZ11** [HelloGitHub-Team/geese#72]
## 月刊部分

- [ ] 月刊增加评分按钮

背景：月刊目前项目名为一个跳转链接，点击即跳转到 GitHub。

思考：HG 目前的网站我理解是想要用户来对用过的进行点评。

建议方案：这块的话需要增加入口，建议可以在目前月刊旁边一个评分项目，点击可跳转到对应的 repo 点评页面。

参考如下：

![image](https://user-images.githubusercontent.com/38887077/197135659-f7c5fae4-56a8-4570-8a49-f5309830bf79.png)

可能潜在的问题：一期月刊这个图标过多。

- [x] 移动端浏览月刊增加目录
- [x] 增加项目详情入口

## 用户个人首页部分

- [x] 用户动态显示具体的项目和评论（过审且已展示的项目），点击项目名和评论可跳转；

## 项目

- [x] 新增项目收藏夹
- [x] 【文案】评论—>精选评论
- [x] 增加评论置顶图标（项目和文章同理）

**Comment by 521xueweihan** [comment]
数据库中表的历史遗留问题已解决，出完月刊就开始开发**收藏夹**功能

**Comment by 521xueweihan** [comment]
@RJM1996 有时间的话，看看怎么给移动端的月刊浏览增加**目录**

“移动端浏览月刊增加目录”

**Comment by 521xueweihan** [comment]
入口已添加，样式的话后面再优化吧～
