### ISSUE TITLE
[产品优化] 首页文章内容标题跳转github等项目地址区域辨识度增强

### ISSUE THREAD

**Issue by Carlos920** [HelloGitHub-Team/geese#74]
![image](https://user-images.githubusercontent.com/32257015/199627586-e26e2f8c-ba0c-49a3-b1d4-748590b763e1.png)
建议增强该区域的辨识度，虽然有hover效果，但是在鼠标不悬停的前提下无法区分或能够快速找到项目地址

**Comment by 521xueweihan** [comment]
@Carlos920 感谢建议，已完成
