### ISSUE TITLE
用户等级

### ISSUE THREAD

**Issue by 521xueweihan** [HelloGitHub-Team/geese#75]
## 背景

显示用户等级以及还需多少贡献值等级

## 需求

样式：

![Image](https://user-images.githubusercontent.com/8255800/200307716-e77f6d71-9827-4d9e-a199-898aeb4ea1bc.png)

图片仅供参考，实现效果以你的想法为准。

位置：

**PC 端**右侧用户头像下面的 Lv1 右边：

![Image](https://user-images.githubusercontent.com/8255800/200307370-028cd021-18c1-4a80-8921-6c18bdcc291f.png)

**移动端** 还没想好放在哪，你看着来。实在没地儿放，就算了。

级别对应的贡献值：

- Lv1：0-99
- Lv2：100-199
- ...
- Lv10：900-999
- Max：>=1000

## 接口

需要登录状态下访问，可找我拿 token。

地址：https://local.api.hellogithub.com/docs#/user/user_me_v1_user_me__get

响应参数：
- level（str）：等级
- next_level_score（int）：到达下一级别所需的总贡献值
例如：
当前等级为 1，则 next_level_score 为 100；
当前等级为 2，则 next_level_score 为 200；

注意：Max 级别对应的 level 为：`Max`，next_level_score 为 `None`

**Comment by RJM1996** [comment]
<img width="264" alt="image" src="https://user-images.githubusercontent.com/33800707/200520550-1e80da94-51a3-4363-8d52-03ff0222c3c4.png">
等级展示需求已提交
