### ISSUE TITLE
开源协议专栏

### ISSUE THREAD

**Issue by 521xueweihan** [HelloGitHub-Team/geese#78]
## 背景

开源协议是创建开源项目和项目走向正规化的必经之路，但是国内针对这部分的内容少之又少，导致大部分的开源作者对这部分不是很了解。

## 需求

HelloGitHub 网站开设一个开源协议的专栏，用来进行开源协议的介绍、特点说明、浏览明细（中文），为用户选择开源提供**中文**的可行性建议，**第一版的主要功能为展示**。

## 功能

首页：

1. 展示权限（permissions）类型的标签
2. 按照最新（last）和最热（hot）排序
3. 可以多选不同权限的（商用、分发、修改、专利）协议，过滤查看项目
4. 简单的翻页功能

##  原型和接口

**优先完成详情页**

### 首页

<img width="822" alt="image" src="https://user-images.githubusercontent.com/8255800/217176472-bc7cd39d-68be-482b-878d-f9276366326f.png">

每行展示几个，可根据实际情况调整

接口：

- 首页：https://local.api.hellogithub.com/docs#/license/index_v1_license__get
    - tid：标签id，可多选例如：?tid=xxx&tid=xxx
- 标签：https://local.api.hellogithub.com/docs#/license/tag_v1_license_tags__get
   - tag_type：默认获取 permissions 类型的标签

### 详情

<img width="798" alt="image" src="https://user-images.githubusercontent.com/8255800/217141890-46300aaa-f16d-4100-ae1f-74410640eb0e.png">

接口：https://local.api.hellogithub.com/docs#/license/license_detail_v1_license__lid__get

参数：
- lid：通过[项目详情接口](https://local.api.hellogithub.com/docs#/repository/detail_v1_repository_detail__rid__get)获取，对应 license_id 字段

细节：
- 标签在 hover 和 点击 的状态下，显示 tag 的 description
- 侧边栏获取指定开源协议的项目，[接口](https://local.api.hellogithub.com/docs#/repository/detail_v1_repository_detail__rid__get) 请求参数为 spdx_id（开源协议详情接口有这个字段）

<img width="442" alt="image" src="https://user-images.githubusercontent.com/8255800/217158739-3bd55ff9-807d-4f1b-9b21-5de989846ef1.png">

### 认领翻译协议

接口：https://local.api.hellogithub.com/docs#/license/claim_license_v1_license__lid__claim__post

**Comment by 521xueweihan** [comment]
@RJM1996 这个需求年前有时间的话就抽空看看，
协议页侧边栏推荐项目那个，我弄成了一个新需求，我弄完详情页改版就搞。

**Comment by 521xueweihan** [comment]
侧边栏项目推荐已完成：https://github.com/HelloGitHub-Team/geese/blob/main/src/components/side/Recommend.tsx

推荐项目接口：https://local.api.hellogithub.com/docs#/repository/recommend_v1_repository_recommend__get

@RJM1996 如果有时间的话，可以先做协议详情页，入口在项目详情处：

![Image](https://user-images.githubusercontent.com/8255800/215923890-e8fa42d8-63b6-4a85-bf61-6347a18652b1.png)

**Comment by RJM1996** [comment]
<img width="1680" alt="page-协议列表" src="https://user-images.githubusercontent.com/33800707/218315599-3488d2df-9f8a-46ad-818e-c998f42a0d0f.png">
<img width="1680" alt="page-协议详情" src="https://user-images.githubusercontent.com/33800707/218315602-a57948e8-111e-4653-9790-737dfe692a59.png">


协议列表和协议详情的整体框架已搭建完毕，剩余工作：
1、点击或鼠标悬浮协议权限等标签的 tooltip 展示
     a. 先自己实现 tooltip 组件，如果效果不太好再考虑是否用第三方插件
     b. 移动端没办法hover，设计交互为点击时使用底部抽屉展示标签说明
2、接口请求相关逻辑处理
3、细节调整，类型问题处理

@521xueweihan

**Comment by 521xueweihan** [comment]
@RJM1996 第一版仅上线了 License 详情页，入口在 PC 访问的开源项目详情页左侧，样式做了优化。

因为，目前 header 位置有限，续会增加和提高 License 入口的优先级。
