### ISSUE TITLE
文章页面的ToTop无法点击

### ISSUE THREAD

**Issue by gjssss** [HelloGitHub-Team/geese#79]
![image](https://user-images.githubusercontent.com/74909529/204137590-a1aae63c-1af2-4a15-a364-101b8b41fb4d.png)
在文章页面下方的`toTop`组件无法工作

**Comment by gjssss** [comment]
:( 好像问题又消失了，不清楚什么原因，昨天点击这个组件是没有反应的，但是现在又变得正常了。

**Comment by 521xueweihan** [comment]
@gjssss 我刚上线了一个新版本，没有复现这个问题。
嗯嗯，后面如果复现的话，可以提供更多的信息，方便我们定位🙏 （浏览器开发者模式的 console 之类的）

**Comment by gjssss** [comment]
@521xueweihan 好的，谢谢你！
