### ISSUE TITLE
以前有个按照语言搜索 现在没了吗？

### ISSUE THREAD

**Issue by djkloop** [HelloGitHub-Team/geese#89]
RT

**Comment by 521xueweihan** [comment]
@djkloop 
![截屏2023-01-13 22 50 28](https://user-images.githubusercontent.com/8255800/212349016-3f918bff-c5eb-4c4e-8ba9-b318a3c6f988.png)

月刊首页在开发中，预计下周上线。

**Comment by 521xueweihan** [comment]
@djkloop 感谢您的支持和反馈，月刊首页已改版上线。

地址：https://hellogithub.com/periodical
