### ISSUE TITLE
评论模块（复杂）

### ISSUE THREAD

**Issue by 521xueweihan** [HelloGitHub-Team/geese#9]
### 需求

展示位置为项目详情页下方，功能类似于豆瓣的评论，功能包含：

![Image](https://user-images.githubusercontent.com/8255800/176829360-92775a8c-fd23-4b73-a091-f9d38ac88c41.png)

打分组件：https://github.com/saadeghi/daisyui

1. 表单包括：用过/没用过+评分+评论（输入框不支持上传图片）
2. 客户端需缓存内容，防止误触导致未发布内容丢失（用户未发布时，缓存评论内容 localStorage）
3. 评论内容均需要通过后台审核后前端才可以显示，所以发布后不可修改
4. 支持最新、热门排序
5. 未登录提示登录后才可以发布
6. 点赞/取消点赞 评论

### 原型图

<img width="756" alt="image" src="https://user-images.githubusercontent.com/8255800/177598420-adb32f3f-512d-4a7e-a5fe-148fffec7c5a.png">

### 接口

**评论：**

1、获取评论列表：https://local.api.hellogithub.com/docs#/comment/index_v1_comment__belong___belong_id__get

请求参数：
    - belong：隶属于那个实体，有限集（repository、article）
    - belong_id：隶属的实体 id
响应：
    - is_voted：当前访问页面的用户，是否对该条评论点过赞（由此判断点赞按钮触发点赞还是取消赞）
    
2、发表项目的评论：https://local.api.hellogithub.com/docs#/comment/repo_create_v1_comment_repository__belong_id__post

请求参数：
    - comment：评论的内容
    - score：评分（整数）
    - is_used：是否用过

**点赞：**

1、点赞：https://local.api.hellogithub.com/docs#/vote/create_vote_v1_vote__belong___belong_id__post

请求参数：
    - belong：隶属于的实体（文章、项目、评论）
    - belong：隶属于实体的 ID
    - item_id：主要用于评论的点赞

文章、项目、评论的点赞用的都是这个接口。如果是项目的评论点赞场景，请求参数则为：belong_id（repo_id)、belong（comment）、item_id（comment_id)

2、取消点赞：https://local.api.hellogithub.com/docs#/vote/delete_vote_v1_vote__delete

**Comment by 521xueweihan** [comment]
@xiaofan9 认领

**Comment by 521xueweihan** [comment]
此组件将在”项目详情页“展示和使用。

这个功能我最初设计的时候仅打做成了一个评论（回复），但思索再三我决定增加”评价“、”有无用过“，所以需要重新设计表然后重写接口，**预计下周一完成。**

**Comment by 521xueweihan** [comment]
@xiaofan9 评论和点赞的接口，已开发完成

**Comment by zhangzhonghe** [comment]
有几个疑问

1. 用户可以多次评论吗？如果可以，那么第二次评论的时候是不是没有必要再次提交评分？
2. **正在审核中**和**未通过审核**的评论，需要面向发起评论者显示对应的状态吗？

**Comment by 521xueweihan** [comment]
@zhangzhonghe 
1. 用户针对一个项目只能评论一次，而且发布后无法修改
2. 审核状态可展示为是否“精选”，我之前设计接口时没考虑到，当前用户已发布过评论的情况。

后面接口会在 data 同级增加一个  current_user_comment 字段，用来填充展示用户已发布过的评论。预计本周五发开发完成
