### ISSUE TITLE
这个项目是前端解决跨域问题还是后端Cros？

### ISSUE THREAD

**Issue by coderbaozi** [HelloGitHub-Team/geese#97]
今天把项目拉下来发现全部是跨域问题，本地端口是localhost:3000 我看了项目结构想知道跨域问题是前端解决的还是Cros

**Comment by 521xueweihan** [comment]
@coderbaozi 这里可以找到答案🙏：https://github.com/HelloGitHub-Team/geese/blob/main/docs/content.md#%E5%BC%80%E5%8F%91%E5%89%8D

**Comment by andrew8baker** [comment]
@521xueweihan 怎么 拿到测试环境登陆的 token 后
